version: '2.1'

services:

  db-server:
    image: yandex/clickhouse-server:latest
    tty: true
    volumes:
      - ./config/config.xml:/etc/clickhouse-server/config.xml
      - ./config/config-preprocessed.xml:/etc/clickhouse-server/config-preprocessed.xml
      - ./config/users-preprocessed.xml:/etc/clickhouse-server/users-preprocessed.xml
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - default

  db-client:
    image: yandex/clickhouse-client:latest
    networks:
      - default

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdca:1::/48
