version: '2.1'

services:

  db-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - default

  db-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    tty: true
    networks:
      - default

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdca:1::/48
